---

driver:
  name: podman

platforms:
  - name: ubuntu-24-04
    image: docker.io/library/ubuntu:24.04
    pre_build_image: true

  - name: oraclelinux-9
    image: docker.io/library/oraclelinux:9
    pre_build_image: true

...